version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build
          command: npm run build

  e2e-tests:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run E2E tests
          command: npm run e2e

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - e2e-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - AND
