version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Build Android Release
          command: ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: release-apk

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
