version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    working_directory: ~/repo

    steps:
      - checkout

      # Rest of your build steps...

      - store_artifacts:
          path: path/to/your/apk
          destination: release

  distribute_ota:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Distribute OTA
          command: |
            # Example command using Firebase App Distribution
            curl -X POST \
              -H "Authorization: Bearer $FIREBASE_TOKEN" \
              -F "app=@path/to/your/apk" \
              -F "release_notes=Updated version" \
              "https://firebase.googleapis.com/v1beta1/{your_firebase_project}/releases"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - distribute_ota:
          requires:
            - build
          filters:
            branches:
              only:
                - AND
