version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build Android Release
          command: cd android && ./gradlew assembleRelease

      - store_artifacts:
          path: android/app/build/outputs/apk/release/
          destination: release

      - store_artifacts:
          path: android/app/build/outputs/apk/debug/
          destination: debug

workflows:
  version: 2
  build-deploy:
    jobs:
      - build