name: Build Android
on:
  push:
    branches: [AND]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Deploy to CodePush
        run:  appcenter codepush release-react -a arhab07ah@gmail.com/cloneApp -d Staging
        
