name: Build Android
on:
  push:
    branches: [AND]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3
      name: Deploy with CodePush

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

      - name: Deploy to CodePush
        run: npx appcenter codepush release-react -a Arhab Muhammad/cloneApp -d Staging -k ${{ secrets.CODEPUSH_DEPLOYMENT_KEY }}
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
