name: Deploy with CodePush

on:
  push:
    branches: [ AND ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

        name: Deploy to CodePush
        run: npx appcenter codepush release-react -a arhab07ah-gmail.com/cloneApp -d Staging
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}

